# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :riakjsononenode do |node_config|
    node_config.vm.box = "precise64"
    node_config.vm.hostname = 'riakjsononenode.localdomain'
    node_config.vm.network :private_network, ip: '10.211.55.121'

    node_config.vm.network :forwarded_port, guest: 8098,  host: 8098  #Riak / RiakJson

    node_config.vm.provider :virtualbox do |vb|
      vb.name = 'riakjson-onenode'
      vb.customize ["modifyvm", :id, "--memory", "5120"]
    end

    node_config.vm.provision :puppet do |puppet|
      puppet.module_path = "puppet/modules/"
      puppet.manifest_file = "site.pp"
      puppet.manifests_path = "puppet"
      puppet.options = "--verbose"
    end
  end
end
